-- Create resumes bucket if not exists
INSERT INTO storage.buckets (id, name, public)
VALUES ('resumes', 'resumes', false)
ON CONFLICT (id) DO NOTHING;

-- Enable RLS
ALTER TABLE storage.objects ENABLE ROW LEVEL SECURITY;

-- Policies for Resumes Bucket

-- 1. Candidates can upload their own resume
CREATE POLICY "Candidates can upload resumes"
ON storage.objects FOR INSERT
TO authenticated
WITH CHECK (bucket_id = 'resumes' AND auth.uid()::text = (storage.foldername(name))[1]);
-- Convention: resumes/{user_id}/{job_id}_{filename}

-- 2. Candidates can view their own resumes
CREATE POLICY "Candidates can view own resumes"
ON storage.objects FOR SELECT
TO authenticated
USING (bucket_id = 'resumes' AND auth.uid()::text = (storage.foldername(name))[1]);

-- 3. Company Members can view resumes for jobs they own
-- This is tricky in Supabase Storage policies due to lack of JOINs/complexity
-- Simplified approach: Allow if they are checking a specific file?
-- BETTER: Use a signed URL for employers when they view the application.
-- So we only strictly need Policy 1 & 2 for the candidate side.
-- The backend (or employer client with signed url) will handle access.
-- Actually, if we use private bucket, we MUST use signed URLs.
-- So Policy 1 & 2 are sufficient for the uploader.
-- Employers will view via Signed URLs generated by the server/client action which has access.
-- Wait, if usage is client-side for upload, yes.
